---
name: TextLinkAds
version: 0.01
author:
  - 'Dave Cardwell <dcardwell@cpan.org>'
abstract: Retrieve Text Link Ads advertiser data
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  File::Spec: 0
  LWP::UserAgent: 0
  XML::Simple: 0
build_requires:
  Test::More: 0
recommends:
  Cache::FileCache: 0
provides:
  TextLinkAds:
    file: lib/TextLinkAds.pm
    version: 0.01
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
